Algoritmo "semnome"

Var
idade : inteiro

Inicio
     escreval("Digite sua idade: ")
     leia(idade)
     
     se (idade >= 0) e  (idade <12) entao
     escreval (" É criança")
     senao
     
     se (idade >=12) e (idade < 18) entao
     escreval("É adolescente")
     senao

     se (idade >18) e (idade<60)
     escreval("É adulto")
     senao
     escreval("É idoso")
     fimse
     
fimse

fimse



Fimalgoritmo