Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
 a:inteiro
  b: inteiro
  c: inteiro
  d: inteiro
  media:real

Inicio

    escreval ("Digite o 1 número: ")
    leia(a)

    escreval ("Digite o 2 número: ")
    leia(b)

    escreval ("Digite o 3 número: ")
    leia(c)
    
    escreval ("Digite o 4 número: ")
    leia(d)
    
    media <- (a + b + c + d) / 4
    escreval("A média é: ", media)


Fimalgoritmo